config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
     resources :orders do
       member do
         get :tracking
         get :reload_tracking
       end
     end
  end
end

app/models/tracking_event.rb
class TrackingEvent < ActiveRecord::Base
  belongs_to :tracking
end

app/views/admin/orders/tracking.html.erb
<div class='toolbar order-links'>
  <%= button_link_to t("edit"), edit_admin_order_url(@order.number), :icon => 'edit' %>
</div>

<%= render :partial => 'admin/shared/order_tabs', :locals => {:current => "Tracking"} %>

<h1><%= "#{t("actions.listing")} #{t("trackings.index")}" %></h1>

<%= image_tag "spinner.gif", :plugin=>"spree", :style => "display:none", :id => 'busy_indicator' %>
<div id="new-tracking"></div>

<%= render "/shared/tracking_table", :locals => {:my_order => @order}%>

app/views/admin/shared/_tracking_tab.html.erb
<% if @order.shipment && !@order.shipment.tracking.blank? %>
  <li>
    <%= link_to t("trackings.index"), tracking_admin_order_path(@order) %>
  </li>
<% end %>

app/views/shared/_tracking_table.html.erb
<%= @order.shipment.tracking %>
<% if current_user.roles.include? Role.find_by_name "admin" %>
  |
  <%= link_to t("trackings.reload"), reload_tracking_admin_order_path(@order)%>
<% end %>
<table class="index">
  <tr>
    <th><%= t("trackings.datetime") %></th>
    <th><%= t("trackings.city") %></th>
    <th><%= t("trackings.event_type") %></th>
    <th><%= t("trackings.delivered_to") %></th>
  </tr>
  <% @order.shipment.tracking_events.each do |tracking_event| %>
    <tr> 
      <td><%=l tracking_event.event_date %></td>
      <td><%= tracking_event.city %></td>
      <td><%= tracking_event.event_type %></td>
      <td><%= tracking_event.delivered_to %></td>
    </tr>
  <% end %>
</table>

app/views/users/_tracking_tables.html.erb
<% if @order %>
  <%= @order.shipment.tracking %>
  <% if current_user.roles.include? Role.find_by_name "admin" %>
    |
    <%= link_to t("trackings.reload"), reload_tracking_admin_order_path(@order)%>
  <% end %>
  <table class="index">
    <tr>
      <th><%= t("trackings.datetime") %></th>
      <th><%= t("trackings.city") %></th>
      <th><%= t("trackings.event_type") %></th>
      <th><%= t("trackings.delivered_to") %></th>
    </tr>
    <% @order.shipment.tracking_events.each do |tracking_event| %>
      <tr> 
        <td><%=l tracking_event.event_date %></td>
        <td><%= tracking_event.city %></td>
        <td><%= tracking_event.event_type %></td>
        <td><%= tracking_event.delivered_to %></td>
      </tr>
    <% end %>
  </table>
<% end %>